feat: add Docker image build and publish workflows; support multi-env docker-compose (#65)
feat: add Docker image build and publish workflows
feat: support multi-env docker-compose config

diff --git a/auto/run-docker-compose b/auto/run-docker-compose
--- a/auto/run-docker-compose
+++ b/auto/run-docker-compose
@@ -3,7 +3,28 @@ set -euo pipefail
 
 cd "$(dirname "$0")/.."
 
-echo "-------------------- Starting Docker Compose --------------------"
-docker compose down -v
-docker compose up -d
+echo "-------------------- 🐳 Starting Docker Compose --------------------"
+
+ENV=${ENV}
+
+if [ "${ENV}" == "local"  ]; then
+  echo "Using local environment configuration"
+  docker_compose_params="deploy/docker-compose.local.yml"
+elif [ "${ENV}" == "test" ]; then
+  echo "Using test environment configuration"
+  docker_compose_params="deploy/docker-compose.test.yml"
+else
+  echo "ENV is not set or invalid, please set ENV to 'test', or 'test'."
+  echo "Exiting..."
+  exit 1
+fi
+
+echo "Render compose files..."
+output="rendered-docker-compose.${ENV}.yml"
+docker compose -f deploy/docker-compose.temp.yml -f "${docker_compose_params}" config > "${output}"
+echo "Rendered file saved to ${output}"
+
+docker compose -f "${output}" down -v
+docker compose -f "${output}" up -d
+
 sleep 20
